apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: tester
    app.kubernetes.io/component: tester
    app.kubernetes.io/instance: tester
    app.kubernetes.io/name: tester
    app.kubernetes.io/part-of: tester
  name: tester
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: tester:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/guignome/tester.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: src/main/docker/Dockerfile.staged-native
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: tester-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: tester-github-webhook-secret
    type: GitHub
  - type: ConfigChange
