apiVersion: v1
kind: ConfigMap
metadata:
  name: tester-config
data:
  tester.yaml: |
    client:
      topology:
        local:
          parallel: 2
          repeat: 1
      endpoints:
      - name: myendpoint
        host: myhost
        port: 443
        protocol: https
        prefix: /myendpoint
      suites:
      - name: suite1
        steps:
        - path: /myservice
          endpoint: myendpoint
          method: POST
          headers:
          - name: header1
            value: value1
          body: |
            { "request" }
    servers:
    - port: 8080
      host: 0.0.0.0
      handlers:
      - path: /*
        method: GET
        delay: 2000
        response: This is a sample response
